# Generated by Django 5.2.6 on 2025-09-14 17:29

import wedding_gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(blank=True, help_text='Ruta del archivo en el almacenamiento (p.ej. images/archivo.jpg)', max_length=512, null=True, unique=True)),
                ('file', models.FileField(help_text='Archivo multimedia subido', upload_to=wedding_gallery.models.get_upload_path)),
                ('mime_type', models.CharField(blank=True, help_text='Tipo MIME del archivo (ej: image/jpeg, video/mp4)', max_length=100)),
                ('media_type', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], help_text='Tipo de media: imagen o video', max_length=10)),
                ('bytes', models.PositiveIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('width', models.PositiveSmallIntegerField(blank=True, help_text='Ancho en píxeles (solo imágenes)', null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, help_text='Alto en píxeles (solo imágenes)', null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Duración en milisegundos (solo videos)', null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Oculto'), (1, 'Visible')], default=1, help_text='1=visible, 0=oculto')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('sha256', models.BinaryField(blank=True, help_text='Hash SHA256 del archivo para deduplicación', max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media Files',
                'db_table': 'media',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='idx_created_at'), models.Index(fields=['media_type', 'created_at'], name='idx_type_created')],
            },
        ),
    ]
